// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiduUVRMBnVEh4BFElEzfchc_vCKf-Yr8',
    appId: '1:211142888702:web:da642e9ed29da0f742a9af',
    messagingSenderId: '211142888702',
    projectId: 'movie-flutter-16765',
    authDomain: 'movie-flutter-16765.firebaseapp.com',
    storageBucket: 'movie-flutter-16765.appspot.com',
    measurementId: 'G-EVG1G4RHD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYpNoX2z_lpiivQQlVX3TN6bWsV5NhNC4',
    appId: '1:211142888702:android:942eca53a454d4ec42a9af',
    messagingSenderId: '211142888702',
    projectId: 'movie-flutter-16765',
    storageBucket: 'movie-flutter-16765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsgjALrOzW_FFWzwJQeh31aAj64my28UQ',
    appId: '1:211142888702:ios:f2b1c4e459ab107342a9af',
    messagingSenderId: '211142888702',
    projectId: 'movie-flutter-16765',
    storageBucket: 'movie-flutter-16765.appspot.com',
    iosClientId:
        '211142888702-cd5dh340k0uqipkh2nsvd849od0gsphb.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie',
  );
}
